server:
  port: 8082
logging:
  config: classpath:logback.xml
spring:
  application:
    name: yao-job
xxl:
  job:
    admin:
      addresses: http://localhost:8080/xxl-job-admin
    accessToken:
    executor:
      appname: xxl-job-demo
      address:
      ip:
      port: 9999
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 10

